apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: nagp-k8s-ashish
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017